### ISSUE TITLE
Is Graft still being pursued?

### ISSUE THREAD

**Issue by timsim00** [GraftJS/graft#27]
Not much activity recently, is this repo still active?  In what way does the death of SPDY (in favor of HTTP/2) effect this project?  Has anyone built out a bigger example that can be open-sourced?  Thanks.

**Comment by AdrianRossouw** [comment]
Hey Drew,

It is still being pursued, but not actively right now. Although I do still mean to pick it up again.

The reason is very much related to what happened to SPDY, but also how that affects the upstream ecosystem.

This is how I responded to the question on our gitter channel recently:

> Robin Venneman:
> Hello, who's still working on GraftJS ? I've been working on a project with Graft for a few months and we're probably going into production soon... wondering when the warning about Graft not being ready for production will be removed?

> AdrianRossouw:
> well, i’m still committed to it, but matteo and the rest are busy with their own things right now.
the code as it’s there, should work, but there has been some stuff happening upstream that made things uncertain
> firstly, libchan, of which jschan is an implementation kind of went dead for a while
largely because SPDY (which it was built on) became a dead standard walking
> and none of the http2 implementations were ready yet
> this is fast changing : https://github.com/indutny/spdy-transport
> so after getting jschan ported to http2, we’d have to consider what the value of trying to keep compatibility with libchan would be
> none of this affects the code that is written on top of graft/libchan really, but has kind of muddied future work a bit. 

As far as bigger example, the closest I can offer is [aetherboard](https://github.com/GraftJS/aetherboard), which has it's own issues to deal with before it can be considered complete.
